### PR TITLE
Generic byte reading things

### PR DESCRIPTION
**Pull request by archer884**
Your comments mentioned making use of generics to cut down on duplicated functions for i32, i16, and u8, as well as for big/little endian reads. I'm not totally sure what you meant by that, and it's a little after one in the morning, but I did scratch together a prototype of sorts.

I'm not sure I'd recommend merging this as is, but it passes the tests and... It's generic. Maybe, if nothing else, it'll help you decide what you'd like to see. My biggest worry is that it seems like I've got two things named almost identically. My gut tells me that this implies an organizational problem of some kind. Like, code that does a thing is split across two places, perhaps for no particularly good reason. That said, even if I am right about that, there's no way my brain is still working well enough to figure out how or why or what to do about it.

I also ran cargo clippy and fixed the things it recommended, and I ran cargo fmt. I realize that this last item might be a cardinal sin, but it's something of a habit and I wasn't really thinking straight. >.>

Edit:

So, uh. I just realized I have no comments of any kind. Please feel free to hit me with questions about anything that doesn't make sense. I mean, that goes without saying, probably, but I thought I'd mention it.

### CODE REVIEW

**Comment by archer884** [comment]
I think I thought of something. Noooot sure. We'll see...

**Comment by archer884** [comment]
I rewrote those two traits into one. Slight improvement? I keep thinking there must be a cleaner way to implement this, but the fact is that Rust does not like treating different length arrays as the same thing.

**Comment by GHvW** [comment]
I don't know why I just saw this (thanks github 😢 ), but I'm seeing this for the first time. I'll review as soon as I can!

**Comment by GHvW** [comment]
I really like this. One thing I don't understand is the Phantom Data. I've tried to learn Phantom Data before, but couldn't wrap my head around the use cases. Any chance you could explain why it's necessary? Feel free to send me a message in the meetup up or something else if you'd prefer to have the conversation outside of github pull request chat 😆

**Comment by archer884** [comment]
@GHvW, I sent you a note on Meetup.

**Pull request closed without merging**
